config/routes.rb
Courses::Application.routes.draw do

  devise_for :users, :controllers => {
    registrations: "registrations",
    sessions:      "sessions"
  }
  
  devise_scope :user do
    post 'login(.:format)',            to: 'sessions#create',    as: "login"
    get  'signout',          to: 'sessions#destroy',   as: "signout"
  end

  namespace :admin do
    resources :users
    resources :faculties
    resources :departments
    resources :documents
    resources :courses do
      resources :term_departments, :term_faculties
      resources :classrooms
      resources :terms do 
        get 'follow', to: 'terms#follow'
      end
      resources :class_topics
      get "new" => "courses#new"
      get "edit" => "courses#edit"
      get ":tab" => "courses#show"
    end
    resources :books, :authors, :book_authors, :references
    resources :tests, controller: "test"
    post 'switch_to', to: 'users#switch_to'
  end

  resources :users
  resources :departments
  resources :profile
  
  resources :terms
  resources :courses
  resources :topics, :sections, :classrooms
  resources :topic_references
  resources :term_documents, :section_document, :topic_documents
  resources :subscriptions

  get 'admin',                to: 'admin/departments#index'
  get 'login',                to: 'home#index'
  get 'getting_started',      to: 'registrations#new',       as: "getting_started"

  get 'download/:id(/:name)', to: 'download#show'

  post 'upload/:tab',         to: 'upload#create'

  get 'about' => 'high_voltage/pages#show', id: 'about'
  get 'contact-us' => 'high_voltage/pages#show', id: 'contact-us'
  get 'help' => 'high_voltage/pages#show', id: 'help'
  get "/pages/*id" => "high_voltage/pages#show", as: :page, format: false

  # get ':slug.json', to: "#{:slug}s#index"
  # get ':slug', to: "#{:slug}s#index"
  get ":slug" => "home#index"
  get ':slug/*route', to: 'home#index'

  root :to => 'home#index'
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :book_cover
  
  has_many :book_authors, :dependent => :destroy
  has_many :authors, :through => :book_authors

  attr_accessible :title, :publisher, :edition, :isbn, :year, :online_retail_url, :book_cover_id, :file_id

  def isbn_10
    Lisbn.new(self.isbn).isbn10
  end

  def isbn_13
    Lisbn.new(self.isbn).isbn13
  end

  def as_json( options = {} )
    {
      id:                  id,
      term_ref_id:         options[:term_ref_id],
      authors:             authors.as_json( only: :name ),
      cover:               book_cover.nil? ? false : book_cover.cover.url(:thumb),
      title:               title,
      publisher:           publisher,
      edition:             edition,
      "isbn-10" =>         isbn_10,
      "isbn-13" =>         isbn_13,
      book_cover_id:       book_cover_id,
      year:                year,
      online_retail_url:   online_retail_url,
    }
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  # GET /books
  # GET /books.json
  def index
    @page_no = params[:page] || 1
    if params[:search]
      @books = Book.where("title like ? or publisher like ?", "%#{params[:search]}%", "%#{params[:search]}%").paginate(:page => @page_no, :per_page => 20)
    else
      @books = Book.paginate(:page => @page_no, :per_page => 20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    @legend = "New Books"

    @authorslist = []
    Author.all.each do |author|
      @authorslist << ["#{author.name}", author.id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    @legend = "Edit Books"

    @authorslist = []
    Author.all.each do |author|
      @authorslist << ["#{author.name}", author.id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        authorlist = params[:authors]
        authors = Set.new
        if not authorlist.nil?
          authorlist.each do |author|
            if author.to_s!="0"
              authors.add({ :book_id => @book.id, :author_id => author })
            end
          end
        end
        authorlist = authors.to_a

        if not authorlist.nil?
          @bookauthor = BookAuthor.create(authorlist)
        else
          @bookauthor = true
        end

        if @bookauthor
          format.html { redirect_to [:admin, @book], notice: 'Book was successfully created.' }
          format.json { render json: @book, status: :created, location: @book }
        else
          format.html { render action: "new" }
          format.json { render json: @bookauthor.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    authorlist = params[:authors]
    authors = Set.new
    if not authorlist.nil?
      authorlist.each do |author|
        if author.to_s!="0"
          authors.add({ :book_id => params[:id], :author_id => author })
        end
      end
    end
    authorlist = authors.to_a

    @destroy_status = BookAuthor.destroy_all(:book_id => params[:id])
    if not authorlist.nil?
      @create_status = BookAuthor.create(authorlist)
    else
      @create_status = true
    end

    respond_to do |format|
      if @book.update_attributes(params[:book]) and @destroy_status and @create_status
        format.html { redirect_to [:admin, @book], notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to admin_books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_form.html.erb
<%= form_for([:admin, @book]) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend><%= @legend %></legend>
    <div class="field">
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>
    <div class="field">
      <%= f.text_field :publisher, class: "form-control", placeholder: "Publisher" %>
    </div>
    <div class="field">
      <%= f.text_field :edition, class: "form-control", placeholder: "Edition" %>
    </div>
    <div class="field">
      <%= f.text_field :isbn, class: "form-control", placeholder: "ISBN Number" %>
    </div>
    <div class="field">
      <%= f.text_field :year, class: "form-control", placeholder: "Year" %>
    </div>
    <div class="field">
      <% if not @book.book_cover.nil? %>
          <img src="<%= p @book.book_cover.cover.url(:thumb) %>"/>
      <% end %>
    </div>
    <div class="field">
      <div id="upload_cover"></div>
    </div>
    <div class="field">
      <%= f.text_field :online_retail_url, class: "form-control", placeholder: "Online Retail URL" %>
    </div>
    <div class="field">
      <%= label_tag(:authors, "Author(s):") %>
      <%= select_tag "authors[]", options_for_select(@authorslist, @book.authors.collect {|author| author.id}), { :multiple => true, :class => "selectpicker show-tick show-menu-arrow", "data-live-search" => "true", :title => "Select Author(s)", "data-header" => "Select Author(s)"  } %>
    </div>
    <div class="actions">
      <a href="<%= url_for admin_books_path %>" class="btn btn-default">
        <span class="glyphicon glyphicon-chevron-left"></span>
          Back
      </a>
      <%= f.submit class: "btn btn-success pull-right" %>
    </div>
  </fieldset>
<% end %>

<script type="text/javascript">
  if(typeof uploadify === 'undefined'){
    var uploadify = new Array();
  }
  uploadify.push({
    "id" : "upload_cover",          // DOM id of the div that uploadify has to be applied
    "multi" : false,                // multiple files?
    "auto" : true,                  // automatically upload files
    "fileTypeDesc" : "Images",      // files type to be allowed
    "fileSizeLimit" : "80000kb",
    "uploader" : "book_cover",
    "buttonText" : "Upload cover Pic",
    "onUploadSuccess" : function(fileObj, res, status){
      // console.log(fileObj);
      // console.log(res);
      // console.log(status);
      res = JSON.parse(res);
      $("#upload_cover-disp").html("");
      $("#upload_cover-queue").parent().append('<div id="upload_cover-disp"></div>');
      $("#upload_cover-disp").html('<img src="'+res["url"]+'">');
      $("#book_cover_id").val(res["id"]);
      $("#upload_cover-queue").parent().append('<input type="hidden" id="book_cover_id" name="book[book_cover_id]" value="'+res["id"]+'">'); 
      $("#book_cover_id").val(res["id"]);
    }
  });
</script>

app/views/admin/books/edit.html.erb
<%= render 'form' %>

app/views/admin/books/index.html.erb
<div class="span12" style="text-align:center">
  <caption><h3>Listing Books</h3></caption>
</div>

<form action="<%= admin_books_path %>" method="get" class="input-group form-group">
  <span class="input-group-addon glyphicon glyphicon-search" style="top: 0; "></span>
  <input type="text" name="search" class="form-control" placeholder="Book Title/publisher">
</form>

<table class="table">
  <div class="pull-right">
    <%= page_navigation_links @books%>
  </div>
  <a href="<%= url_for new_admin_book_path %>" class="btn btn-default">
    <span class="glyphicon glyphicon-plus" style="color: green;"></span>
    New Book
  </a>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Edition</th>
      <th>Actions</th>
    </tr>
  </thead>

<% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to book.title, [:admin, book] %>
      (<%= book.year %>)<br />
      <strong>ISBN:</strong>
      <%= book.isbn.empty? ? "Not Found": book.isbn %>
    </td>  
    <td>
      <% if book.authors.length == 0 %>
      No author found for this book.
      <a href="<%= url_for edit_admin_book_path(book) %>" class="btn btn-xs btn-primary">Add author</a>
      <% else %>
      <div>
	<% book.authors.each do |author| %>
	<div><%= link_to author.name, [:admin, author] %></div>
	<% end %>
      </div>
      <% end %>
    </td>
    <td><%= book.publisher %></td>
    <td><%= book.edition %></td>
    <td>
      <a href="<%= url_for edit_admin_book_path(book) %>" class="btn btn-default">
	<span class="glyphicon glyphicon-pencil" style="color: #322dd2;"></span>
      </a>
      <a href="<%= url_for [:admin, book] %>" class="btn btn-default" data-method="delete" data-confirm="Are you sure?" rel="nofollow">
        <span class="glyphicon glyphicon-trash" style="color: #d2322d;"></span>
      </a>
    </td>
  </tr>
<% end %>
</table>

<div class="pull-right">
  <%= page_navigation_links @books%>
</div>
<a href="<%= url_for new_admin_book_path %>" class="btn btn-default">
  <span class="glyphicon glyphicon-plus" style="color: green;"></span>
  New Book
</a>

app/views/admin/books/new.html.erb
<%= render 'form' %>

app/views/admin/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pull-right">
  <%= link_to 'Edit', edit_admin_book_path(@book), class: "btn btn-default btn-small" %>
  <%= link_to 'Back', admin_books_path, class: "btn btn-default btn-small" %>
</div>
<div class="s-push"></div>

<table class="table table-hover">
  <thead>
    <caption>
      <h3>Book Details</h3>
    </caption>
  </thead>
  <tbody>  
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author(s)</th>
      <td>
  <% if @book.authors.length == 0 %>
    No author found for this book.
      <%= link_to 'Add Author', edit_admin_book_path(@book) %>
	<% else %>
	<ul>
    <% if not @book.authors.nil? %>
  	  <% @book.authors.each do |author| %>
  	  <li><%= link_to author.name, [:admin, author] %></li>
      <% end %>
	  <% end %>
	</ul>
	<% end %>
      </td>
    </tr>
    <tr>
      <th>Publisher</th>
      <td><%= @book.publisher %></td>
    </tr>
    <tr>
      <th>Edition</th>
      <td><%= @book.edition %></td>
    </tr>
    <tr>
      <th>ISBN</th>
      <td><%= @book.isbn %></td>
    </tr>
    <tr>
      <th>Year</th>
      <td><%= @book.year %></td>
    </tr>
    <tr>
      <th>Online Retail URL:</th>
      <td><a href="<%= @book.online_retail_url %>"><%= @book.online_retail_url %></a></td>
    </tr>
    <% if not @book.book_cover.nil? %>
      <tr>
        <th>Cover Pic:</th>
        <td><img src="<%= p @book.book_cover.cover.url(:large) %>"/></td>
      </tr>
    <% end %>

  </tbody>
</table>