config/routes.rb
Courses::Application.routes.draw do

  devise_for :users, :controllers => {
    registrations: "registrations",
    sessions:      "sessions"
  }
  
  devise_scope :user do
    post 'login(.:format)',            to: 'sessions#create',    as: "login"
    get  'signout',          to: 'sessions#destroy',   as: "signout"
  end

  namespace :admin do
    resources :users
    resources :faculties
    resources :departments
    resources :documents
    resources :courses do
      resources :term_departments, :term_faculties
      resources :classrooms
      resources :terms do 
        get 'follow', to: 'terms#follow'
      end
      resources :class_topics
      get "new" => "courses#new"
      get "edit" => "courses#edit"
      get ":tab" => "courses#show"
    end
    resources :books, :authors, :book_authors, :references
    resources :tests, controller: "test"
    post 'switch_to', to: 'users#switch_to'
  end

  resources :users
  resources :departments
  resources :profile
  
  resources :terms
  resources :courses
  resources :topics, :sections, :classrooms
  resources :topic_references
  resources :term_documents, :section_document, :topic_documents
  resources :subscriptions

  get 'admin',                to: 'admin/departments#index'
  get 'login',                to: 'home#index'
  get 'getting_started',      to: 'registrations#new',       as: "getting_started"

  get 'download/:id(/:name)', to: 'download#show'

  post 'upload/:tab',         to: 'upload#create'

  get 'about' => 'high_voltage/pages#show', id: 'about'
  get 'contact-us' => 'high_voltage/pages#show', id: 'contact-us'
  get 'help' => 'high_voltage/pages#show', id: 'help'
  get "/pages/*id" => "high_voltage/pages#show", as: :page, format: false

  # get ':slug.json', to: "#{:slug}s#index"
  # get ':slug', to: "#{:slug}s#index"
  get ":slug" => "home#index"
  get ':slug/*route', to: 'home#index'

  root :to => 'home#index'
  
end

app/models/term_department.rb
class TermDepartment < ActiveRecord::Base
  belongs_to :term
  belongs_to :department
  
  has_one :course, :through => :term

  attr_accessible :term_id, :department_id  
  validates_uniqueness_of :term_id, :scope => :department_id
end

app/controllers/admin/term_departments_controller.rb
class Admin::TermDepartmentsController < Admin::BaseController
  # GET /term_departments
  # GET /term_departments.json
  def index
    @course = Course.find(params[:course_id])
    @terms_array = @course.terms.collect do |term|
      term.id
    end
    @term_departments = TermDepartment.find_all_by_term_id(@terms_array)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @term_departments }
    end
  end

  # GET /term_departments/1
  # GET /term_departments/1.json
  def show
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.find(params[:id])
    @term = @term_department.term

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term_department }
    end
  end

  # GET /term_departments/new
  # GET /term_departments/new.json
  def new
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.new
    @legend = "New term_department"
    @terms_array = @course.terms.collect do |term|
      ["##{term.id} #{term.course.subject_code} #{term.year} - #{term.semester.ordinalize} semester", term.id]
    end
    @departments_array = Department.all.collect do |department|
      [department.name, department.id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term_department }
    end
  end

  # GET /term_departments/1/edit
  def edit
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.find(params[:id])
    @legend = "Edit term_department"

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @term_department }
    end
  end

  # POST /term_departments
  # POST /term_departments.json
  def create
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.new(params[:term_department])

    respond_to do |format|
      if @term_department.save
        format.html { redirect_to [:admin, @course], notice: 'Term department was successfully created.' }
        format.json { render json: @term_department, status: :created, location: @term_department }
      else
        flash = flash
        format.html { redirect_to [:admin, @course] }
        format.json { render json: @term_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /term_departments/1
  # PUT /term_departments/1.json
  def update
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.find(params[:id])

    respond_to do |format|
      if @term_department.update_attributes(params[:term_department])
        format.html { redirect_to [:admin, @course, @term_department], notice: 'Term department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @term_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /term_departments/1
  # DELETE /term_departments/1.json
  def destroy
    @course = Course.find(params[:course_id])
    @term_department = TermDepartment.find(params[:id])
    @term_department.destroy

    respond_to do |format|
      format.html { redirect_to [:admin, @course] }
      format.json { head :no_content }
    end
  end
end

app/helpers/term_departments_helper.rb
module TermDepartmentsHelper
end

app/views/admin/term_departments/_form.html.erb
<%= form_for([:admin, @course, @term_department]) do |f| %>
  <% if @term_department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term_department.errors.count, "error") %> prohibited this term_department from being saved:</h2>

      <ul>
      <% @term_department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend><%= @legend %></legend>
  <div class="field">
    <%= f.label :term_id %>
    <%= f.select :term_id, options_for_select(@terms_array) %>
  </div>
  <div class="field">
    <%= f.label :department_id %>
    <%= f.select :department_id, options_for_select(@departments_array) %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Back', [:admin, @course, :terms], class: "btn btn-default btn-small" %>
  </div>
<% end %>

app/views/admin/term_departments/edit.html.erb
<h1>Editing term_department</h1>

<%= render 'form' %>

<%= link_to 'Show', @term_department %> |
<%= link_to 'Back', term_departments_path %>

app/views/admin/term_departments/index.html.erb
<h3>Listing term_departments</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Term</th>
      <th>Department</th>
      <th>Actions</th>
    </tr>
  </thead>
  
  <tbody> 
    <% @term_departments.each do |term_department| %>
    <% term =  term_department.term %>
    <tr>
      <td>
	<%= "##{term.id} #{term.course.subject_code} #{term.year} - #{term.semester.ordinalize} semester" %>
      </td>
      <td><%= term_department.department.name %></td>
      <td>
	<%= link_to 'Show', term_department %>
	<%= link_to 'Edit', edit_term_department_path(term_department) %>
	<%= link_to 'Destroy', term_department, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to "New Term department", [:new, :admin, @course, :term_department], class: "btn btn-primary" %>

app/views/admin/term_departments/new.html.erb
<%= render 'form' %>

app/views/admin/term_departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Term:</b>
  <%= "##{@term.id} #{@term.course.subject_code} #{@term.year} - #{@term.semester.ordinalize} semester" %>
</p>

<p>
  <b>Department:</b>
  <%= @term_department.department.name %>
</p>


<%= link_to 'Edit', [:edit, :admin, @course, @term_department] %> |
<%= link_to 'Back', [:admin, @course, :term_departments] %>