config/routes.rb
Courses::Application.routes.draw do

  devise_for :users, :controllers => {
    registrations: "registrations",
    sessions:      "sessions"
  }
  
  devise_scope :user do
    post 'login(.:format)',            to: 'sessions#create',    as: "login"
    get  'signout',          to: 'sessions#destroy',   as: "signout"
  end

  namespace :admin do
    resources :users
    resources :faculties
    resources :departments
    resources :documents
    resources :courses do
      resources :term_departments, :term_faculties
      resources :classrooms
      resources :terms do 
        get 'follow', to: 'terms#follow'
      end
      resources :class_topics
      get "new" => "courses#new"
      get "edit" => "courses#edit"
      get ":tab" => "courses#show"
    end
    resources :books, :authors, :book_authors, :references
    resources :tests, controller: "test"
    post 'switch_to', to: 'users#switch_to'
  end

  resources :users
  resources :departments
  resources :profile
  
  resources :terms
  resources :courses
  resources :topics, :sections, :classrooms
  resources :topic_references
  resources :term_documents, :section_document, :topic_documents
  resources :subscriptions

  get 'admin',                to: 'admin/departments#index'
  get 'login',                to: 'home#index'
  get 'getting_started',      to: 'registrations#new',       as: "getting_started"

  get 'download/:id(/:name)', to: 'download#show'

  post 'upload/:tab',         to: 'upload#create'

  get 'about' => 'high_voltage/pages#show', id: 'about'
  get 'contact-us' => 'high_voltage/pages#show', id: 'contact-us'
  get 'help' => 'high_voltage/pages#show', id: 'help'
  get "/pages/*id" => "high_voltage/pages#show", as: :page, format: false

  # get ':slug.json', to: "#{:slug}s#index"
  # get ':slug', to: "#{:slug}s#index"
  get ":slug" => "home#index"
  get ':slug/*route', to: 'home#index'

  root :to => 'home#index'
  
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :hod, :class_name => "Faculty"

  has_many :term_departments, :dependent => :destroy
  has_many :terms, :through => :term_departments
  has_many :courses, :through => :term_departments

  attr_accessible :name, :short, :rollno_prefix, :hod_id


  def as_json( options = {} )
    dept = {
      id:            self[:id],
      name:          self[:name],
      rollno_prefix: self[:rollno_prefix],
      short:         self[:short],
      hod:           hod_name,
      hod_email:     hod_email
    }

    
    if options[:include] == :course_listing
      dept[:course_listing] = course_listing
    end

    dept
  end

  private
  
  def course_listing

    self.terms.select(&:this_year?).group_by(&:semester).map do |sem, term|
      {
        semester:    sem,
        course_list: term.as_json
      }
    end

  end

  def hod_name
      if self.hod.nil?
        "-"
      else
        self.hod.full_name
      end
  end
  
  def hod_email
      if self.hod.nil?
        0
      else
        self.hod.user.email
      end
  end

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::BaseController
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])
    @current_sem = nil
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @legend = "New Department"
    @department = Department.new
    @faculties_array = []
    Faculty.all.each do |fac|
      if fac.department == @department
        @faculties_array << [fac.full_name, fac.id]
      end
    end
    @hod = nil
 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @legend = "Edit Department"
    @department = Department.find(params[:id])
    @courses_array = Course.all.map do |course|
      ["#{course.subject_code} - #{course.name}", course.id]
    end
    @faculties_array = []
    # This should be done using sql join - commented by vignesh
    Faculty.all.each do |fac|
      if fac.department == @department
        @faculties_array << [fac.full_name, fac.id]
      end
    end
    @hod = @department.hod.nil? ? nil : @department.hod.id

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @department }
    end
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to [:admin, @department], notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to [:admin, @department], notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to admin_departments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    respond_to do |format|
      format.html { render "home/dashboard" }
      format.json { render json: Department.all.collect { |dept| dept.as_json } }
    end
  end

  def show
    respond_to do |format|
      format.html { render "home/dashboard" }
	  
      format.json {
        dept = get_dept params[:id]

        if dept.nil?
          render json: { status: "Page Not Found" }, status: 404
        else
          render json: dept.as_json(include: :course_listing)
        end
      }
    end
  end

  private

  def get_dept(id)
    if id.match(/^[[:alpha:]]+$/)
      dept = Department.find_by(:short => params[:id])
    else
      dept = Department.find(params[:id])
    end
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= form_for([:admin, @department]) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend><%= @legend %></legend>
    
    <div class="field">
      <%= f.text_field :short, class: "form-control", placeholder: "Short Form. eg: CSE" %>
    </div>
    <div class="field">
      <%= f.text_field :name, class: "form-control", placeholder: "Department Name" %>
    </div>
    <div class="field">
      <%= f.select :hod_id, options_for_select(@faculties_array, @hod), {}, {:class => "selectpicker show-tick show-menu-arrow", "data-live-search" => "true", :title => "Select HOD", "data-header" => "Select a HOD" } %>
    </div>
    <div class="field">
      <%= f.text_field :rollno_prefix, class: "form-control", placeholder: "Roll Number Prefix" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary btn-large" %>
      <%= link_to "Back", admin_departments_path, class: "btn btn-default btn-small" %>
    </div>
  </fieldset>
<% end %>

app/views/admin/departments/edit.html.erb
<%= render 'form' %>

app/views/admin/departments/index.html.erb
<div class="span12" style="text-align:center">
  <caption><h3>Departments</h3></caption>
</div>
<a href="<%= url_for new_admin_department_path %>" class="btn btn-default btn-small">
  <span class="glyphicon glyphicon-plus" style="color: green; "></span> 
  Add Department
</a>
<br />
<br />

<table class="table">
  <thead>
    <tr>
      <th>Department Name</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @departments.length == 0 %>
    <tr>
      <td colspan="5">
      No department was found in the database. Click <%= link_to "here", new_admin_department_path %> to add new department.
      </td>
    </tr>
    <% else %>
    <% @departments.each do |department| %>
    <tr>
      <td><%= link_to department.name, admin_department_path(department), class: 'btn btn-small btn-link' %></td>
      <td><%= link_to 'Edit', edit_admin_department_path(department), class: 'btn btn-default btn-small' %></td>
      <td><%= link_to 'Remove', [:admin, department], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br />

<a href="<%= url_for new_admin_department_path %>" class="btn btn-default btn-small">
  <span class="glyphicon glyphicon-plus" style="color: green; "></span> 
  Add Department
</a>

app/views/admin/departments/new.html.erb
<%= render 'form' %>

app/views/admin/departments/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <a href="<%= url_for admin_departments_path %>" class="btn btn-default btn-small">
    <i class="glyphicon glyphicon-chevron-left"></i>
  </a>
  <small><%= @department.short %></small>
  <%= @department.name %>
  <table class="pull-right">
    <tr>
      <td><%= link_to 'Edit', edit_admin_department_path(@department), class: 'btn btn-default btn-small pull-right' %></td>
      <td><%= link_to 'Remove', [:admin, @department], method: :destroy, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger pull-right' %></td>
    </tr>
  </table>
</h3>

<div>
  Headed by <strong><%= @department.hod.nil? ? "-" : @department.hod.full_name %></strong>.
</div>

<table class="table table-hover">
  <caption>
    <h3>Courses offered</h3>
  </caption>
  <thead>
    <tr>
      <th>Course</th>
      <th>Faculty</th>
      <th>Credits</th>
    </tr>
  </thead>
  <% if @department.courses.length==0 %>
  <tbody><tr>
    <td>No course found for this department.</td>
  </tr></tbody>
  <% else %>
  <tbody>
    <% @department.terms.each do |term| %>
    <% if term.semester != @current_sem %>
    <% @current_sem = term.semester  %>
    <tr>
      <th colspan="3"><%= @current_sem.ordinalize %> semester</strong></th>
    </tr>
    <% end %>
    <tr>
      <td><%= link_to term.course.name, [:admin, term.course] %></td>
      <td>
	<% term.faculties.each do |faculty| %>
	<span class="label label-info"><%= faculty.user.email %></span>
	<% end %>
      </td>
      <td><%= "#{term.course.credits}" %></td>
    </tr>
    <% end %>
  </tbody>
  <% end %>
</table>