config/routes.rb
Courses::Application.routes.draw do

  devise_for :users, :controllers => {
    registrations: "registrations",
    sessions:      "sessions"
  }
  
  devise_scope :user do
    post 'login(.:format)',            to: 'sessions#create',    as: "login"
    get  'signout',          to: 'sessions#destroy',   as: "signout"
  end

  namespace :admin do
    resources :users
    resources :faculties
    resources :departments
    resources :documents
    resources :courses do
      resources :term_departments, :term_faculties
      resources :classrooms
      resources :terms do 
        get 'follow', to: 'terms#follow'
      end
      resources :class_topics
      get "new" => "courses#new"
      get "edit" => "courses#edit"
      get ":tab" => "courses#show"
    end
    resources :books, :authors, :book_authors, :references
    resources :tests, controller: "test"
    post 'switch_to', to: 'users#switch_to'
  end

  resources :users
  resources :departments
  resources :profile
  
  resources :terms
  resources :courses
  resources :topics, :sections, :classrooms
  resources :topic_references
  resources :term_documents, :section_document, :topic_documents
  resources :subscriptions

  get 'admin',                to: 'admin/departments#index'
  get 'login',                to: 'home#index'
  get 'getting_started',      to: 'registrations#new',       as: "getting_started"

  get 'download/:id(/:name)', to: 'download#show'

  post 'upload/:tab',         to: 'upload#create'

  get 'about' => 'high_voltage/pages#show', id: 'about'
  get 'contact-us' => 'high_voltage/pages#show', id: 'contact-us'
  get 'help' => 'high_voltage/pages#show', id: 'help'
  get "/pages/*id" => "high_voltage/pages#show", as: :page, format: false

  # get ':slug.json', to: "#{:slug}s#index"
  # get ':slug', to: "#{:slug}s#index"
  get ":slug" => "home#index"
  get ':slug/*route', to: 'home#index'

  root :to => 'home#index'
  
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  belongs_to :user
  attr_accessible :prefix, :user_id, :designation, :about
  
  validates :user_id, :uniqueness => true

  def department
    Department.find(user.department_id)
  end
  
  def full_name
    "#{prefix} #{user.name}"
  end

  def as_json( options = {} )
    faculty = {
      id:    id,
      name:  full_name,
      email: user.email,
      about: Kramdown::Document.new(about || "").to_html
    }
    
    faculty.except(options[:exclude])
  end
  
end

app/controllers/admin/faculties_controller.rb
class Admin::FacultiesController < Admin::BaseController
  # GET /faculties
  # GET /faculties.json
  def index
    @page_no = params[:page] || 1
    if params[:search]
      user_list = User.where("email like ? or name like ? or phone like ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").pluck(:id)
      @faculties = Faculty.where(:user_id => user_list).paginate(:page => @page_no, :per_page => 20)
    else
      @faculties = Faculty.paginate(:page => @page_no, :per_page => 20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faculties }
    end
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
    @faculty = Faculty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faculty }
    end
  end

  # GET /faculties/new
  # GET /faculties/new.json
  def new
    @legend = "New Faculty"
    @faculty = Faculty.new
    @user_id = nil 
    @users_array = [["",-1]]
    User.all.each do |user|
      if not user.student?
        @users_array << [user.email, user.id]
      end
    end
    @prefix_array = [["",""],["Dr.","Dr."],["Prof.","Prof."],["Ms.","Ms."],["Mr.","Mr."],["Mrs.","Mrs."]]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faculty }
    end
  end

  # GET /faculties/1/edit
  def edit
    @legend = "Edit Faculty"
    @faculty = Faculty.find(params[:id])
    @prefix_array = [["",""],["Dr.","Dr."],["Prof.","Prof."],["Ms.","Ms."],["Mr.","Mr."],["Mrs.","Mrs."]]

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @faculty }
    end
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(params[:faculty])

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to [:admin, @faculty], notice: 'Faculty was successfully created.' }
        format.json { render json: @faculty, status: :created, location: @faculty }
      else
        format.html { render action: "new" }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faculties/1
  # PUT /faculties/1.json
  def update
    @faculty = Faculty.find(params[:id])

    respond_to do |format|
      if @faculty.update_attributes(params[:faculty])
        format.html { redirect_to [:admin, @faculty], notice: 'Faculty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty = Faculty.find(params[:id])
    @faculty.destroy

    respond_to do |format|
      format.html { redirect_to admin_faculties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/admin/faculties/_form.html.erb
<%= form_for([:admin, @faculty]) do |f| %>
<% if @faculty.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

  <ul>
    <% @faculty.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset>
  <legend><%= @legend %></legend>
  <div class="field">
    <%= f.select :prefix, options_for_select(@prefix_array, @faculty.prefix), {}, { :class => "selectpicker show-tick show-menu-arrow", :title => "Select Prefix", "data-header" => "Select Prefix"} %>
  </div>
  <% if @legend == "Edit Faculty" %>
    <div class="field">
      <%= text_field_tag :name, @faculty.user.name, :readonly => true, :placeholder => "name", :class => "form-control" %>
    </div>
    <div class="field">
      <%= text_field_tag :email, @faculty.user.email+"@nitt.edu", :readonly => true, :placeholder => "Email id without @nitt.edu", :class => "form-control" %>
    </div>
  <% else %>
    <div class="field">
      <%= f.select :user_id, options_for_select(@users_array, @user_id), {}, {:class => "selectpicker show-tick show-menu-arrow", "data-live-search" => "true", :title => "Select email id", "data-header" => "Select email id"} %>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :designation, :class => "form-control", :placeholder => "Designation" %>
  </div>
  <div class="form-group">
    <p class="help-block small pull-right">*About is parsed with <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" class="external" target="_blank">Markdown</a></p>
    <%= f.text_area :about, :rows => 10, :cols => 40, :class => "form-control", :placeholder => "About the faculty" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-success pull-right" %>
    <%= link_to "Back", admin_faculties_path, class: "btn btn-default btn-small" %>
  </div>
</fieldset>
<% end %>

app/views/admin/faculties/edit.html.erb
<%= render 'form' %>

app/views/admin/faculties/index.html.erb
<div class="span12" style="text-align:center">
  <caption><h3>Listing all Faculties</h3></caption>
</div>

<form action="<%= admin_faculties_path %>" method="get" class="input-group form-group">
  <span class="input-group-addon glyphicon glyphicon-search" style="top: 0; "></span>
  <input type="text" name="search" class="form-control" placeholder="Name/Email/Phone">
</form>

<table class="table table-hover">
  <div class="pull-right">
    <%= page_navigation_links @faculties%>
  </div>

  <a href="<%= url_for new_admin_faculty_path %>" class="btn btn-default pull-left">
    <span class="glyphicon glyphicon-plus" style="color: green; "></span>
    New Faculty
  </a>

  <thead>
    <tr>
      <th>Faculty</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @faculties.each do |faculty| %>
    <tr>
      <td><%= link_to faculty.prefix+" "+faculty.user.name , [:admin, faculty] %></td>
      <td><%= faculty.user.email %>@nitt.edu</td>
      <td>
        <%= link_to 'Show', [:admin, faculty], class: "btn btn-default btn-mini" %>
        <%= link_to 'Edit', edit_admin_faculty_path(faculty), class: "btn btn-default btn-mini" %>
        <%= link_to 'Remove', [:admin, faculty], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right">
  <%= page_navigation_links @faculties%>
</div>
<a href="<%= url_for new_admin_faculty_path %>" class="btn btn-default pull-left">
  <span class="glyphicon glyphicon-plus" style="color: green; "></span>
  New Faculty
</a>

app/views/admin/faculties/new.html.erb
<%= render 'form' %>

app/views/admin/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Faculty Info</b>
</p>

<p>
	<table>
		<tr>
			<td>Name:</td>
			<td><%= @faculty.prefix %><%= @faculty.user.name %></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><%= @faculty.user.email %>@nitt.edu</td>
		</tr>
		<tr>
			<td>Designation:</td>
			<td><%= @faculty.designation %></td>
		</tr>
		<tr>
			<td>About:</td>
			<td><%= Kramdown::Document.new(@faculty.about).to_html.html_safe %></td>
		</tr>
	</table>
</p>


<%= link_to 'Edit', edit_admin_faculty_path(@faculty), class: "btn btn-default" %>
<%= link_to 'Back', admin_faculties_path, class: "btn btn-default btn-small" %>